config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index'

  get 'jobs/index'

  get 'jobs/new'

  get 'pages/index'

  get 'pages/careers'
  
  get 'pages/about'

  get 'pages/contact'

  get 'pages/customers'

  get 'pages/info_sys'

  get 'pages/languages'

  get 'pages/medical'

  get 'pages/solutions'

  get 'pages/specialized_training'

  get 'pages/staffing'

  

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  resources :jobs 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form",
      :to => "degarmo@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/job.rb
class Job < ApplicationRecord
	validates :title, presence: true
	validates :company, presence: true
	validates :pay, presence: true
	validates :location, presence: true
	validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception

  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end

  
  private

  def contact_params
    params.
    require(:contact).
    permit(:name, :email, :message).
    except(:nickname).
    merge(request: request)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :require_login, only: [:edit, :create, :new]
	

  def index
    @job = Job.page(params[:page]).per(10).order(created_at: :desc)
  end

  def new
  	@job = Job.new
  end

  def create
  	@job = Job.new(params.require(:job).permit(:title, :company, :pay, :location, :description))
  	if @job.save
  	 redirect_to jobs_path
  	else
  	 render "new"
  	end
  end

  def show
    find_job
  end

  def edit
    find_job
  end

  def update
    find_job
    if @job.update(params.require(:job).permit(:title, :company, :pay, :location, :description))
      flash[:notice] = "Successfully update job!"
      redirect_to jobs_path
    else
      flash[:notice] = "Error updating job!"
      render 'edit'
    end
  end

  private

  def jobs_params
    params.require(:title).permit(:title, :company, :pay, :description)
  end

  def find_job
    @job = Job.find(params[:id])
  end

  def create_archive
    find_job.archive = true
    find_job.save
    redirect_to jobs_path
  end

  def destroy_archive
    find_job.archive = false
    find_job.save
    redirect_to jobs_path
  end

  
end

app/controllers/p_controller.rb
class PController < ApplicationController
  def index
  end

  def about
  end

  def solutions
  end

  def customers
  end

  def specialized_training
  end

  def info_sys
  end

  def languages
  end

  def medical
  end

  def staffing
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  

  def index

  end

  def about

  end

  def contact

  end

  def customers

  end

  def info_sys

  end

  def languages

  end

  def medical

  end

  def solutions

  end

  def specialized_training

  end

  def staffing

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archive_helper.rb
module ArchiveHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="/" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<% provide(:title, "Send FDR A Message") %>
<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>Contact FDR</h1>
            </div>
        </div>
    </div>
</div>
<hr>


    <div id="content">
            <div class="container" id="contact">

                <div class="row">
                    <div class="col-md-8">

                        <section>

                            <div class="heading">
                                <h2>We are here to help you</h2>
                            </div>

                            <p class="lead">We're looking to create a world that allows each citizen live in peace</p>
                            <p>Please feel free to contact us, our customer service center is working for you 24/7.</p>

                            <div class="heading">
                                <h3>Contact form</h3>
                            </div>

                            <form>
                                <div class="row">
                                  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="firstname">Firstname</label>
                                            <%= f.input :name, :required => true, :class => "form-control" %>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="email">Email</label>
                                            <%= f.input :email, :required => true, :class => "form-control" %>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label for="message">Message</label>
                                            <%= f.input :message, :as => :text, :required => true, :class => "text-hght form-control" %>
                                              <div class= "hidden">
                                                <%= f.input :nickname, :hint => 'Leave this field blank!' %>
                                              </div>
                                        </div>
                                    </div>

                                    <div class="col-sm-12 text-center">
                                        <section><i class=""><%= f.button :submit, 'Send message', :class=> "btn btn-template-main" %></section> 
                                        <% end %>
                                    </div>
                                </div>
                                <!-- /.row -->
                            </form>
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d41517.00031774483!2d-78.89376490562782!3d35.06900245076819!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89ab134f42924a23%3A0xa3ab9e7512763b9b!2sFayetteville%2C+NC!5e0!3m2!1sen!2sus!4v1485310833531" width="800" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

                        </section>

                    </div>

                    <div class="col-md-4">

                        <section>

                            <h3 class="text-uppercase">Address</h3>

                            <p>FDR Inc
                                <br>2935 Breezewood Ave.
                                <br>Suite 101
                                <br>Fayetteville, NC 28303
                                <br>
                                <strong>United States of America</strong>
                            </p>

                            <h3 class="text-uppercase">Call </h3>

                            
                            <p><i class="fa fa-phone-square" aria-hidden="true"></i><strong> (910)868-9996</strong></p>
                            <p>Fax<strong> (910)323-3683</strong></p>

                     
                        </section>

                    </div>

                </div>
                <!-- /.row -->


            </div>
        </div>  <!-- /#contact.container -->
     </div>
<section class="bar no-mb color-white">
  <div class="container">
      <div class="row">
        <div class="col-md-12">
              
            </div>
        </div>
    </div>
</section>
</div>

app/views/jobs/_form.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<%= simple_form_for @job do |form|%>
			<%= form.input :title, label: "Job Title" %>
			<%= form.input :company, label: "Agency" %>
			<%= form.input :pay, label: "Compensation" %> 
			<%= form.input :location, label: "Location" %>
			<%= form.input :description, label: "Details", :size => 4000 %>
			<%= form.button :submit %>
		<% end %>
	</div>
</div>	

app/views/jobs/edit.html.erb
<% provide(:title, "Edit Job: #{@job.title} || Job ID: #{@job.id}") %>
<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1><%= "Edit Job: #{@job.title}" %></h1>
            </div>
        </div>
    </div>
</div>
<hr>
<div id="content">
  <div class="container">
        <div class="col-md-2">
        	
        </div>
        
        <div class="col-md-8">
        	<%= render 'form', job: @job %>
        </div>
        
        <div class="col-md-2">
        	
        </div>
      </div>
    </div>
</div>
<hr>
  <br>
    <section class="bar no-mb color-white">
        <div class="container">
            <div class="row">
              <div class="col-md-12">
                    
                  </div>
              </div>
          </div>
      </section>
  </div>

app/views/jobs/index.html.erb
<% provide(:title, "Jobs") %>
<div id="heading-breadcrumbs">
            <div class="container">
                <div class="row">
                    <div class="col-md-7">
                        <h1>Jobs</h1>
                    </div>
                    <div class="col-md-5">
                       
                    </div>
                </div>
            </div>
        </div>
<div id="content">
	<div class="container">

	    <div class="row">

	        <!-- *** LEFT COLUMN ***
	 _________________________________________________________ -->
		<div class="col-md-2">
	
		</div>
		<div class="col-md-8">
		  	<% @job.each do |job| %>
			<div class="panel panel-default">
		    	<div class="panel-body">
					<div class="page-header"> 	
			  	      <h1><%= link_to job.title, job %> <small> <%= job.location %></small></h1>
				      <h4><p>$<%= job.pay%></p></h4>
				      <p><%= truncate(job.description, :length => 350) %></p>
				      <p><%= link_to "Read More", job, :class => "btn btn-lg btn-info" %></p>
				    </div>
			    </div>
			</div>
			<% end %>
        </div>
		
		<div class="col-md-2">
  	    
  	    </div>
	<div class="row">
		<div class="col-md-4">
			
		</div>

		<div class="col-md-4 center-block">
			<p><%= paginate @job, :class => "pagination" %></p>
		</div>

		<div class="col-md-4"></div>
		
		</div>

	                
	        </div>
	 	  </div>
	    </div>
	  </div>
        <div id="get-it">
            <div class="container">
            	<div class="col-md-2">
            		
            	</div>
                <div class="col-md-8 col-sm-12">
                    <h2>Victorious warriors win <br>first and then go to war,
                    <br>while defeated warriors go to war <br>first and then seek to win. <h3>Sun Tzu</h3></h2>
                </div>
                <div class="col-md-2 col-sm-12">
                   
                </div>
            </div>
        </div>


        <!-- *** GET IT END *** -->

app/views/jobs/new.html.erb
<% provide(:title, "Create Job") %>
    
<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1><%= "Create Job" %></h1>
            </div>
        </div>
    </div>
</div>
<hr>
<div id="content">
  <div class="container">  
    <div class="row">
      <div class="col-md-2">
      	
      </div>
      
      <div class="col-md-8">
      	<div class="text-center"><h1>Submit New Position</h1></div>
      	<%= render partial: "form" %>	
      </div>
      
      <div class="col-md-2">
      	
      </div>
    </div>
  </div>
</div>
    <hr>
    <br>
      <section class="bar no-mb color-white">
          <div class="container">
              <div class="row">
                <div class="col-md-12">
                      
                    </div>
                </div>
            </div>
        </section>
    </div>

app/views/jobs/show.html.erb
<% provide(:title, "Job Title: #{@job.title} // Job ID:  #{@job.id}") %>
    
<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1><%= "Job: #{@job.title}" %></h1>
            </div>
        </div>
    </div>
</div>
<hr>

<div id="content">
	<div class="container">
		<div class="row">
			<br>
			<div class="col-md-2"></div>
			
			<div class="col-md-8">
				<div class="col-md-8">
					<div class="page-header">
						<h1><%= @job.title %> <small><%= @job.location %></small></h1>
						
					</div>
				</div>	
				<div class="col-md-4">
					<div class="text-center">
						<br>
						<h3>$<%= @job.pay %></h3>
						<h4>ID: <%= @job.id %></h4>
						
					</div>
				</div>
				<div class="col-md-1"></div>
				<div class="col-md-10">
					<div>
						<%= @job.description %>
					</div>
					<br>			
					<% if current_user %>
		              <%= link_to "Edit Job", edit_job_path, :class => "btn btn-info" %> |
		            <% else %>
		            	<br>
		              <%= link_to "Apply", "#", :class => "btn btn-primary" %>
		              <br>
		            <% end %>
					<br>
				</div>
				<div class="col-md-1"></div>
			</div>
			
			<div class="col-md-2"></div>
		</div>
	</div>
		<hr>
		<br>
	    <section class="bar no-mb color-white">
        	<div class="container">
          		<div class="row">
            		<div class="col-md-12">
                    	
                    </div>
                </div>
            </div>
        </section>
    </div>



		

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-inverse">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">FDR Inc.</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", '#' %></li>
        <li><%= link_to "Customers", pages_customers_path %></li>
        <li><%= link_to "Opportunities", jobs_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Services<span class="caret"></span></a>
          <ul class="dropdown-menu">
          	<li><%= link_to "Information Technology", pages_info_sys_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Medical Industry", pages_medical_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Staffing", pages_staffing_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Specialized Training", pages_specialized_training_path %></li>
            <li role="separator" class="divider"></li>
			<li><%= link_to "Languages", pages_languages_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<li><%= link_to " Login", sign_in_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/pages/about.html.erb
<% provide(:title, "About") %>

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>About FDR</h1>
            </div>
        </div>
    </div>
</div>
<hr>
<div id="content">
            <div class="container">
                <section>
                    <div class="row">

                        <div class="col-md-12 clearfix">

                            <div id="text-page">

                                <p class="lead">This page's aim is to show you the most common HTML elements appearance on the website. For further reference please visit official <a href="http://getbootstrap.com/css/" class="external">Bootstrap website</a>.</p>

                                <h1>Text formatting - Header level 1</h1>

                                <p><strong>Pellentesque habitant morbi tristique</strong> senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas
                                    semper. <em>Aenean ultricies mi vitae est.</em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae</code>, ornare sit amet, wisi.
                                    Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href="#">Donec non enim</a> in turpis pulvinar facilisis. Ut felis.</p>

                                <h2>Header Level 2</h2>

                                <ol>
                                    <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
                                    <li>Aliquam tincidunt mauris eu risus.</li>
                                </ol>

                                <blockquote>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna. Cras in mi at felis aliquet congue. Ut a est eget ligula molestie gravida. Curabitur massa. Donec eleifend, libero at sagittis mollis, tellus est
                                        malesuada tellus, at luctus turpis elit sit amet quam. Vivamus pretium ornare est.</p>
                                </blockquote>

                                <h3>Header Level 3</h3>

                                <ul>
                                    <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
                                    <li>Aliquam tincidunt mauris eu risus.</li>
                                </ul>

                                <hr>

                                <h2>Images</h2>

                                <div class="row">
                                    <div class="col-md-4">
                                        <p class="text-center">
                                            <img src="img/detailsquare.jpg" class="img-circle img-responsive" alt="">
                                        </p>
                                        <p class="text-center">circle</p>
                                    </div>
                                    <div class="col-md-4">
                                        <p class="text-center">
                                            <img src="img/detailsquare.jpg" class="img-thumbnail img-responsive" alt="">
                                        </p>
                                        <p class="text-center">thumbnail</p>
                                    </div>
                                    <div class="col-md-4">
                                        <p class="text-center">
                                            <img src="img/detailsquare.jpg" class="img-rounded img-responsive" alt="">
                                        </p>
                                        <p class="text-center">rounded</p>
                                    </div>
                                </div>

                            </div>


                        </div>
                        <!-- /.col-md-12 -->
                    </div>
                    <!-- /.row -->
                </section>
            </div>
            <!-- /.container -->
        </div>
        <!-- /#content -->


        <!-- *** GET IT ***
_________________________________________________________ -->

<section class="bar no-mb color-white">
	<div class="container">
  		<div class="row">
    		<div class="col-md-12">
                <hr>            	
            </div>
        </div>
    </div>
</section>
</div>

app/views/pages/careers.html.erb
<% provide(:title, "Careers" %>

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>Careers</h1>
            </div>
        </div>
    </div>
</div>
<hr>
<div id="content">
	<div class="container">
		





	</div>
<section class="bar no-mb color-white">
	<div class="container">
  		<div class="row">
    		<div class="col-md-12">

            </div>
        </div>
    </div>
</section>
</div>

app/views/pages/contact.html.erb
<% provide(:title, "Contact Us") %>

app/views/pages/index.html.erb
<% provide(:title, "Home") %>
        <section class="no-mb">
            <!-- *** JUMBOTRON ***
 _________________________________________________________ -->

            <div class="jumbotron">

                <div class="dark-mask"></div>

                <div class="container">
                    <div class="row mb-small">
                        <div class="col-sm-12 text-center">
                            <h1>OUR MISSION</h1>
                            <h2></h2>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-6 mb-small">
                            <i class="fa fa-globe fa-4x" aria-hidden="true" ></i>
                        </div>

                        <div class="col-sm-6 text-center-xs">
                            <p class="text-uppercase">To Deliver Quality Solutions,
                                <br>Steadfast Dedication To our clients needs
                                <br>At home or around the globe    
                                </p>
                            <p>Join our team!</p>
                            <p><%= link_to "Join The Team", jobs_path, :class => "scroll-to btn btn-template-transparent-black" %></a>
                            </p>

                        </div>
                    </div>
                </div>
            </div>

            <!-- *** JUMBOTRON END *** -->
        </section>

        <section class="bar background-gray no-mb padding-big text-center-sm">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <h2 class="text-uppercase">Services <small>Highlight</small></h2>
                        <p class="lead mb-small">Staffing</p>
                        <p class="mb-small">FDR's hardwork and dedicaton will make finding the right candidate <strong>the easiest part of your human resources experience</strong>. If you're for one skilled nurse or team of engineers, we can make your staffing headaches go away. Trust FDR Inc.</p>

                        <p><%= link_to "Read More", pages_staffing_path, :class => "btn btn-template-main" %></a>
                        </p>
                    </div>
                    <div class="col-md-6 text-center">
                        <img src="../assets/staffing.jpg" alt="" class="img-responsive">
                    </div>
                </div>
            </div>
        </section>

        <section class="bar no-mb color-white padding-big text-center-sm">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 text-center">
                        <img src="../assets/careers.jpg" alt="" class="img-responsive">
                    </div>
                    <div class="col-md-6">
                        <h2 class="text-uppercase">Work for FDR</h2>
                        <p class="lead mb-small">Travel the world and get paid</p>
                        <p class="mb-small">We pay top dollar for the talent that helps shape the world and it's citizens. We'll work hard for you because we know you'll work hard for us.</p>

                        <%= link_to "Careers", jobs_path, :class => "btn btn-template-transparent-primary" %> 
                        </p>
                    </div>
                </div>
            </div>
        </section>

        <section class="bar background-gray no-mb padding-big text-center-sm">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <h2 class="text-uppercase">Contact FDR</h2>
                        <p class="mb-small">Our dedicated team will work around the clock to deliver a solution for your team. Contact us to talk about how FDR can help you or your business.</p>

                        <%= link_to "Contact Us", contacts_path, :class => "btn btn-template-main"%>
                        </p>
                    </div>
                    <div class="col-md-6 text-center">
                        <img src="../assets/contactus.jpg" alt="" class="img-responsive">
                    </div>
                </div>
            </div>
        </section>
<!-- Middle Section needs filling out

















-->
      
        <section class="bar background-image-fixed-2 no-mb color-white text-center">
            <div class="dark-mask"></div>
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="icon icon-lg"><i class="fa fa-bolt fa-lg"></i>
                        </div>
                        <h1>Want to know more about FDR?</h1>
                        <p class="lead">With more than 60 years combined military and special forces training, we're <br>the best at spotting talent and getting the job done.</p>
                        <p class="text-center">
                        <%= link_to "About FDR", pages_about_path, :class => "btn btn-template-transparent-black btn-lg"%>
                        </p>
                    </div>

                </div>
            </div>
        </section>

        <!-- *** GET IT ***
_________________________________________________________ -->

        <div id="get-it">
            <div class="container">
                <div class="col-md-8 col-sm-12">
                    <h3>Who's working wtih FDR Inc.?</h3>
                </div>
                <div class="col-md-4 col-sm-12">
                    <%= link_to "FDR Partners", pages_customers_path, :class =>"btn btn-template-transparent-primary" %>
                </div>
            </div>
        </div>


        <!-- *** GET IT END *** -->

app/views/pages/info_sys.html.erb
<% provide(:title, "Information Systems") %>

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>Information Systems</h1>
            </div>
        </div>
    </div>
</div>
<hr>
<div id="content">
	<div class="container">
		



	</div>
<section class="bar no-mb color-white">
	<div class="container">
  		<div class="row">
    		<div class="col-md-12">
            	
            </div>
        </div>
    </div>
</section>
</div>

app/views/pages/languages.html.erb
<% provide(:title, "Languages") %>

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>Languages</h1>
            </div>
        </div>
    </div>
</div>
<hr>
<div id="content">
	<div class="container">
		



	</div>
<section class="bar no-mb color-white">
	<div class="container">
  		<div class="row">
    		<div class="col-md-12">
            	
            </div>
        </div>
    </div>
</section>
</div>

app/views/pages/medical.html.erb
<% provide(:title, "Medical Industry") %>

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>Medical</h1>
            </div>
        </div>
    </div>
</div>
<hr>
<div id="content">
	<div class="container">
		




	</div>
<section class="bar no-mb color-white">
	<div class="container">
  		<div class="row">
    		<div class="col-md-12">
            	
            </div>
        </div>
    </div>
</section>

</div>

app/views/pages/solutions.html.erb
<% provide(:title, "Solutions") %>

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>Solutions</h1>
            </div>
        </div>
    </div>
</div>
<hr>
<div id="content">
	<div class="container">
		
	</div>
</div>





<section class="bar no-mb color-white">
	<div class="container">
  		<div class="row">
    		<div class="col-md-12">
            	
            </div>
        </div>
    </div>
</section>

app/views/pages/specialized_training.html.erb
<% provide(:title, "Specialized Training") %>

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>Sign in</h1>
            </div>
        </div>
    </div>
</div>
<hr>

<div id="content">
	<div class="container">
		
	</div>
<section class="bar no-mb color-white">
	<div class="container">
  		<div class="row">
    		<div class="col-md-12">
            	
            </div>
        </div>
    </div>
</section>
</div>

app/views/pages/staffing.html.erb
<% provide(:title, "Staffing") %>

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>Sign in</h1>
            </div>
        </div>
    </div>
</div>
<hr>
<div id="content">
	<div class="container">
		


		
	</div>
<section class="bar no-mb color-white">
	<div class="container">
  		<div class="row">
    		<div class="col-md-12">
            	
            </div>
        </div>
    </div>
</section>
</div>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>